import { COLORS } from "../theme";

export const MIN_SIZE = {
  button: { w: 40, h: 40 },
  gas: { w: 40, h: 100 },
  mfd: { w: 320, h: 220 },
  drs: { w: 60, h: 40 },
  paddle: { w: 90, h: 46 },
  flag: { w: 70, h: 40 },
  default: { w: 60, h: 30 },
  macro: { w: 55, h: 55 },
};

export function buildCatalog() {
  return [
    { id: "X", type: "button", label: "X", color: COLORS.cyan, w: 65, h: 65 },
    { id: "Y", type: "button", label: "Y", color: COLORS.yellow, w: 55, h: 55 },
    { id: "A", type: "button", label: "A", color: COLORS.green, w: 60, h: 60 },
    { id: "B", type: "button", label: "B", color: COLORS.red, w: 60, h: 60 },
    {
      id: "Dpad_Up",
      type: "button",
      label: "⇧",
      color: COLORS.textDim,
      w: 50,
      h: 50,
    },
    {
      id: "Dpad_Dn",
      type: "button",
      label: "⇩",
      color: COLORS.textDim,
      w: 50,
      h: 50,
    },
    {
      id: "Dpad_L",
      type: "button",
      label: "⇦",
      color: COLORS.textDim,
      w: 50,
      h: 50,
    },
    {
      id: "Dpad_R",
      type: "button",
      label: "⇨",
      color: COLORS.textDim,
      w: 50,
      h: 50,
    },
    { id: "LB", type: "paddle", label: "－", side: "left", w: 100, h: 50 },
    { id: "RB", type: "paddle", label: "＋", side: "right", w: 100, h: 50 },
    { id: "R2", type: "r2", label: "R2", w: 180, h: 180 },
    { id: "GAS", type: "gas", label: "GAS", w: 60, h: 180 },
    { id: "DASH", type: "mfd", label: "MFD", w: 350, h: 230 },
    { id: "DRS", type: "drs", label: "DRS", w: 70, h: 40 },
    { id: "FLAG", type: "flag", label: "FLAG", w: 90, h: 45 },
    {
      id: "START",
      type: "button",
      label: "START",
      color: COLORS.textDim,
      w: 70,
      h: 45,
    },
    {
      id: "SELECT",
      type: "button",
      label: "SEL",
      color: COLORS.textDim,
      w: 70,
      h: 45,
    },
    {
      id: "L3",
      type: "button",
      label: "L3",
      color: COLORS.textDim,
      w: 55,
      h: 55,
    },
    {
      id: "R3",
      type: "button",
      label: "R3",
      color: COLORS.textDim,
      w: 55,
      h: 55,
    },

    // ---> TOMBOL MAKRO LU MASUK SINI <---
    {
      id: "MACRO_OT",
      type: "macro",
      label: "OT",
      color: COLORS.blue,
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_PL",
      type: "macro",
      label: "PL",
      color: COLORS.yellow,
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_BB_PLUS",
      type: "macro",
      label: "BB+",
      color: COLORS.red,
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_BB_MINUS",
      type: "macro",
      label: "BB-",
      color: COLORS.red,
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_DRS",
      type: "macro",
      label: "DRS",
      color: "#00FF00",
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_ERS_PLUS",
      type: "macro",
      label: "ERS +",
      color: "#FFD700",
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_ERS_MINUS",
      type: "macro",
      label: "ERS -",
      color: "#FF8C00",
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_DIFF_PLUS",
      type: "macro",
      label: "DIFF +",
      color: "#00E5FF",
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_DIFF_MINUS",
      type: "macro",
      label: "DIFF -",
      color: "#FF0055",
      w: 60,
      h: 60,
    },
    {
      id: "MACRO_RADIO",
      type: "macro",
      label: "RADIO",
      color: "#800080",
      w: 60,
      h: 60,
    },
  ];
}

export function buildInitialLayout(SCREEN_W, SCREEN_H) {
  return [
    {
      id: "A",
      type: "button",
      label: "A",
      color: COLORS.green,
      x: SCREEN_W - 90,
      y: 90,
      w: 60,
      h: 60,
    },
    {
      id: "B",
      type: "button",
      label: "B",
      color: COLORS.red,
      x: SCREEN_W - 60,
      y: 180,
      w: 60,
      h: 60,
    },
    {
      id: "LB",
      type: "paddle",
      label: "－",
      side: "left",
      x: 20,
      y: 26,
      w: 100,
      h: 50,
    },
    {
      id: "RB",
      type: "paddle",
      label: "＋",
      side: "right",
      x: SCREEN_W - 120,
      y: 26,
      w: 100,
      h: 50,
    },
    {
      id: "DASH",
      type: "mfd",
      label: "MFD",
      x: SCREEN_W / 2 - 175,
      y: SCREEN_H / 2 - 120,
      w: 350,
      h: 230,
    },
    {
      id: "DRS",
      type: "drs",
      label: "DRS",
      x: SCREEN_W / 2 + 100,
      y: 35,
      w: 70,
      h: 40,
    },
    {
      id: "FLAG",
      type: "flag",
      label: "FLAG",
      x: SCREEN_W / 2 - 45,
      y: 35,
      w: 90,
      h: 45,
    },
  ];
}
